### ISSUE TITLE
Trying to create an oracle jdbc driver for syndesis

### ISSUE THREAD

**Issue by jvivallos** [syndesisio/syndesis-extensions#105] opened 2021-08-07 23:02 UTC
What I've been using on the pom is

groupId com.oracle.ojdbc 
artifactId jdbc-driver 
version 1.0 
scope system 
systemPath ${project.basedir}/lib/ojdbc7.jar

then I run

mvn clean install -DsyndesisServerUrl=https://syndesis... (our sindesis server)

and finally

./mvnw -pl :syndesis-library-jdbc-driver clean package

This final step is what throws an error, and even though it generates a .jar and It gets accepted as a new extension it doesn't register the oracle thin driver

**Comment by zregvart** [comment] 2021-08-09 08:24
Duplicate of #104

**Closed by zregvart** 2021-08-09 08:24 UTC
